model:
  latent_dim: 128
  encoder:
    - convolution:
        in_channels: 1
        out_channels: 16
        kernel_size: 3
        stride: 2
        padding: 1
      activation: selu
    - convolution:
        in_channels: 16
        out_channels: 32
        kernel_size: 3
        stride: 2
        padding: 1
      activation: selu
    - convolution:
        in_channels: 32
        out_channels: 64
        kernel_size: 3
        stride: 2
        padding: 1
      activation: selu
    - convolution:
        in_channels: 64
        out_channels: 128
        kernel_size: 3
        stride: 2
        padding: 1
      activation: selu
    - convolution:
        in_channels: 128
        out_channels: 256
        kernel_size: 3
        stride: 2
        padding: 1
      activation: selu
  decoder:
    - convolution:
        in_channels: 256
        out_channels: 128
        kernel_size: 3
        stride: 2
        padding: 1
        output_padding: 1
      activation: selu
    - convolution:
        in_channels: 128
        out_channels: 64
        kernel_size: 3
        stride: 2
        padding: 1
        output_padding: 1
      activation: selu
    - convolution:
        in_channels: 64
        out_channels: 32
        kernel_size: 3
        stride: 2
        padding: 1
        output_padding: 1
      activation: selu
    - convolution:
        in_channels: 32
        out_channels: 16
        kernel_size: 3
        stride: 2
        padding: 1
        output_padding: 1
      activation: selu
    - convolution:
        in_channels: 16
        out_channels: 1
        kernel_size: 3
        stride: 2
        padding: 1
        output_padding: 1
      activation: tanh