training: 
  optimizer: adam
  loss: l1
  epochs: 80
  lr: 0.0001

data:
  root_dir: /local/eb/aa5506/MIMIC-CXR-JPG/mimic-cxr-jpg/2.1.0/
  num_workers: 8
  metadata: /local/eb/aa5506/MIMIC-CXR-JPG/mimic-cxr-jpg/2.1.0/mimic-cxr-2.0.0-metadata.csv
  batch_size: 64

output: 
  ckpt_dir: /local/eb/aa5506/feature_extractors/ckpt/
  log_dir: /local/eb/aa5506/feature_extractors/logs/
  tensorboard_dir: /local/eb/aa5506/feature_extractors/tensorboard/
  emb_dir: /local/eb/aa5506/feature_extractors/embeddings/
  img_dir: /local/eb/aa5506/feature_extractors/images/

model:
  path: /local/eb/aa5506/feature_extractors/models/autoencoder/
  name: autoencoder


device: cuda