data:
  # dataset_root: /local/eb/aa5506/MIMIC-CXR-JPG/mimic-cxr-jpg/2.1.0/files/  
  # annotations_csv: /local/eb/aa5506/MIMIC-CXR-JPG/mimic-cxr-jpg/2.1.0/mimic-cxr-2.0.0-metadata.csv
  # allowed_views: ['AP', 'PA']
  # image_size: 224
  # num_workers: 8
  path: /insomnia001/depts/edu/COMSE6998/aa5506/causal-fairness/synth_data/data/synth_data_0148_32x32_big.pt
  batch_size: 256
  image_size: 32
  num_workers: 8
  val_ratio: 0.2

simclr:
  encoder:
    arch: resnet
    in_channels: 1
    resnet_layers: [1, 1, 1, 1]
    bottleneck_dim: 128

  projection_head:
    hidden_dim: 128
    output_dim: 128

  loss:
    temperature: 0.05
    lambda_uniformity: 0.4

  optimizer:
    name: sgd
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0001
    max_epochs: 1000
  
  pl: 
    log_progress_bar: false
    enable_progress_bar: false

  save_dir: ckpt/encoder

oracle:
  in_channels: 1
  covariate_dim: 2
  hidden_dim: 128
  lr: 0.001
  weight_decay: 0.0001
  batch_size: 64
  max_epochs: 20
  save_dir: ./ckpt/oracle

  pl: 
    log_progress_bar: true

student:
  encoder_ckpt: /insomnia001/depts/edu/COMSE6998/aa5506/causal-fairness/feature_extractors/SimCLR/ckpt/encoder/simclr-epoch=487-train_loss_ssl=0.6879.ckpt
  teacher_ckpt: /insomnia001/depts/edu/COMSE6998/aa5506/causal-fairness/feature_extractors/SimCLR/ckpt/oracle/teacher-epoch=24-val_loss=0.16.ckpt
  fine_tune_encoder: true
  hidden_dim: 32
  covariate_dim: 2
  lr: 0.001
  batch_size: 64
  max_epochs: 10
  save_dir: ./ckpt/student
  lambda_sup: 0.5
  lambda_align: 1

  pl: 
    log_progress_bar: true

logging:
  log_interval: 10
  eval_interval: 1
  seed: 42
  enable_progress_bar: true