data:
  dataset_root: /local/eb/aa5506/MIMIC-CXR-JPG/mimic-cxr-jpg/2.1.0/files/  
  annotations_csv: /local/eb/aa5506/MIMIC-CXR-JPG/mimic-cxr-jpg/2.1.0/mimic-cxr-2.0.0-metadata.csv
  allowed_views: ['AP', 'PA']
  image_size: 224
  num_workers: 8

simclr:
  encoder_arch: resnet18
  projection_dim: 128
  batch_size: 256
  epochs: 100
  temperature: 0.5
  learning_rate: 1e-3
  weight_decay: 1e-6
  save_dir: ./ckpt/

oracle:
  encoder_arch: densenet121
  pretrained_weights: torchxrayvision
  freeze_encoder: true
  hidden_dim: 256
  dropout: 0.1
  lr: 1e-3
  batch_size: 32
  epochs: 25
  save_path: ./here

student:
  encoder_init: /path/to/simclr/checkpoints/best.pt
  fine_tune_encoder: true
  hidden_dim: 128
  output_dim: 1
  lr: 1e-3
  batch_size: 32
  epochs: 50
  save_path: /path/to/student.pt

sufficiency:
  lambda: 1.0          
  compress_l2: 0.01            
  representation_dim: 64 

logging:
  log_interval: 10
  eval_interval: 1
  results_dir: /path/to/results/
  seed: 42
