data:
  # dataset_root: /local/eb/aa5506/MIMIC-CXR-JPG/mimic-cxr-jpg/2.1.0/files/  
  # annotations_csv: /local/eb/aa5506/MIMIC-CXR-JPG/mimic-cxr-jpg/2.1.0/mimic-cxr-2.0.0-metadata.csv
  # allowed_views: ['AP', 'PA']
  # image_size: 224
  # num_workers: 8
  path: /insomnia001/depts/edu/COMSE6998/aa5506/causal-fairness/synth_data/data/synth_data_0148_32x32_big.pt
  batch_size: 256
  image_size: 32
  num_workers: 8
  val_ratio: 0.2

simclr:
  encoder:
    arch: resnet
    in_channels: 1
    resnet_layers: [1, 1, 1, 1]
    bottleneck_dim: 128

  projection_head:
    hidden_dim: 128
    output_dim: 128

  loss:
    temperature: 0.05
    lambda_uniformity: 0.4

  optimizer:
    name: sgd
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0001
    max_epochs: 1000
  
  pl: 
    log_progress_bar: false
    enable_progress_bar: false

  
  save_dir: ckpt/

oracle:
  encoder_arch: densenet121
  pretrained_weights: torchxrayvision
  freeze_encoder: true
  hidden_dim: 256
  dropout: 0.1
  lr: 1e-3
  batch_size: 32
  epochs: 25
  save_path: ./here

student:
  encoder_init: /path/to/simclr/checkpoints/best.pt
  fine_tune_encoder: true
  hidden_dim: 128
  output_dim: 1
  lr: 1e-3
  batch_size: 32
  epochs: 50
  save_path: /path/to/student.pt

sufficiency:
  lambda: 1.0          
  compress_l2: 0.01            
  representation_dim: 64 

logging:
  log_interval: 10
  eval_interval: 1
  results_dir: /path/to/results/
  seed: 42
  enable_progress_bar: false